"""switch schemas

Revision ID: 15e1e7a7c917
Revises: d57d7950c732
Create Date: 2025-01-29 20:56:22.250480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e1e7a7c917'
down_revision: Union[str, None] = 'd57d7950c732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'path')
    # ### end Alembic commands ###
