"""init

Revision ID: 297c19984515
Revises: 
Create Date: 2024-11-14 16:29:56.258958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '297c19984515'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doors', sa.Integer(), nullable=False),
    sa.Column('loops', sa.Enum('TEST', name='doorsloops'), nullable=True),
    sa.Column('platbands', sa.BOOLEAN(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.Date(), nullable=False),
    sa.Column('order_status', sa.Enum('TEST', name='orderstatus'), nullable=False),
    sa.Column('description_id', sa.Integer(), nullable=False),
    sa.Column('reviews_id', sa.Integer(), nullable=True),
    sa.Column('deadlines_id', sa.Integer(), nullable=False),
    sa.Column('complexity', sa.Enum('JUNIOR', 'MIDDLE', 'SENIOR', name='ordercomplexity'), nullable=True),
    sa.Column('workers', sa.JSON(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviews', sa.TEXT(), nullable=False),
    sa.Column('rating', sa.Enum('TEST', name='ratingorder'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'WORKER', 'CLIENT', 'MANAGER', name='roleuser'), nullable=False),
    sa.Column('date_registration', sa.Date(), nullable=False),
    sa.Column('adress', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.TEXT(), nullable=False),
    sa.Column('last_name', sa.TEXT(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('level_worker', sa.Enum('JUNIOR', 'MIDDLE', 'SENIOR', name='levelworker'), nullable=False),
    sa.Column('rating', sa.FLOAT(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workers')
    op.drop_table('users')
    op.drop_table('reviews')
    op.drop_table('orders')
    op.drop_table('descriptions')
    op.drop_table('deadlines')
    # ### end Alembic commands ###
