"""fix

Revision ID: 5287a4151090
Revises: 47e88dea2939
Create Date: 2024-11-14 19:54:00.373712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5287a4151090'
down_revision: Union[str, None] = '47e88dea2939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'orders', 'reviews', ['reviews_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'descriptions', ['description_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'deadlines', ['deadlines_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'workers', 'users', ['worker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    # ### end Alembic commands ###
