"""init3

Revision ID: a22bb0587779
Revises: 5287a4151090
Create Date: 2024-11-18 11:36:20.712866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a22bb0587779'
down_revision: Union[str, None] = '5287a4151090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date_registration',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'date_registration',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
