"""add image in task

Revision ID: ec01a9cc6f27
Revises: 1477d5d3d274
Create Date: 2025-01-31 01:16:01.931746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec01a9cc6f27'
down_revision: Union[str, None] = '1477d5d3d274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('image_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'image_id')
    # ### end Alembic commands ###
